# project name
project_name: "project-buxus"

# input : path to genome information file
input_file:
  leaf_genome_info: "/Genomes.txt"
  synteny_file_name: ".CDS-CDS.last.tdd10.cs0.filtered.dag.all.go_D20_g10_A5.aligncoords.gcoords.ks.txt"
  synteny_file_path: "/"
  phylo_tree_path: "/phyloTree.txt"
  jar_path: "."

# output : paths to output files
output_file:
  gene_list: "/gene_list.txt"
  gene_family: "/GeneFamily.txt"
  genomes: "/GenomeString.txt"
  mwm_input_template: "/mwminputAnc"
  mwm_output_template: "/mwmoutputAnc"
  contig_template: "/contigAnc"
  dcj_output_path: "/dcj_output"
  dcj_summary_path: "/dcj_summary.txt"

# input path
input_path: "../inputData/"

# output path
output_path: "../outputData/"


## Global parameters


# range of percent identity of ortholog pairs
min_cutoff_weight: 65
max_cutoff_weight: 100

# window size
ws: 7

# minimum adjacency weight to be considered for maximum weight matching
min_mwm_weight: 100

# gene family size para1: the maximum number of genes in a gene family
gf1: 50

# gene family size para2: the maximum number of genes from a genome in a gene family
gf2: 10

# gene family size para3: the minimum number of genomes in a gene family
gf3: 1

# specify the desired number of ancestral chromosomes
K: 7

## set thresholds
ctgLen: 1   ## minimum length in each contig
nctg: 250    ## only include first nctg contigs

## threshold of distance (1MB) between two genes in the same contig on the same chromosome
## if the distance between two genes is smaller than the threshold, merge them into one block
DIS.threshold: 1000000

## threshold to visualize the gene/block (150 kb)
## if a block is less than this length, do not show it --> keep the plot clean
blockLEN.threshold: 150000


## threshold for coocurrence analysis
## only count blocks that are longer than 15KB
lenBLK.threshold: 15000







